config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'on_call_periods#index'

  resource :on_call_period, only: [:create]
  resources :on_call_units, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  validates :name, presence: true

  has_many :on_call_units
end

app/models/on_call_period.rb
class OnCallPeriod < ApplicationRecord
  validates :start_date, presence: true
  validates :end_date, presence: true

  has_many :on_call_units

  validates_with DateValidator

  def to_date
    "#{start_date.strftime('%a, %d %b %Y')} ~ #{end_date.strftime('%a, %d %b %Y')}"
  end

  private

  def next_number
    last = OnCallPeriod.last.presence
    return 1 unless last.present?

    last.number + 1
  end
end

app/models/on_call_unit.rb
class OnCallUnit < ApplicationRecord
  validates :start_date, presence: true
  validates :end_date, presence: true

  belongs_to :member
  belongs_to :on_call_period

  validates_with DateValidator

  def to_date
    "#{start_date.strftime('%a, %d %b %Y')} ~ #{end_date.strftime('%a, %d %b %Y')}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/on_call_periods_controller.rb
# frozen_string_literal: true

class OnCallPeriodsController < ApplicationController
  def index
    @on_call_period = OnCallPeriod.new
    @first_on_call_date ||= OnCallPeriod.first&.start_date
    @last_on_call_date ||= OnCallPeriod.last&.end_date
    current_on_call_member
    search_date
    on_call_schedules
  end

  def create # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
    start_date = new_period_start_date
    end_date = (start_date + members.count.weeks) - 1.day

    ActiveRecord::Base.transaction do
      period = OnCallPeriod.create(start_date: start_date.to_s, end_date: end_date.to_s)

      members.each do |member|
        end_date = (start_date + 6.days).end_of_day
        OnCallUnit.create(on_call_period: period, member: member, start_date: start_date.to_s, end_date: end_date.to_s)
        start_date += 1.week
      end

      flash[:success] = "Period #{period.id}(#{period.to_date}) created successfully."
    end

    redirect_to root_path
  rescue StandardError => e
    Rails.logger.error e
    flash[:error] = 'Unexpected error occurred. Please try again.'
    redirect_back(fallback_location: root_path)
  end

  private

  def current_on_call_member
    time_now = Time.now.to_s
    @current_on_call_member ||= OnCallUnit.find_by('start_date < ? AND end_date > ?', time_now, time_now)&.member
  end

  def on_call_schedules
    @schedules = OnCallUnit.where('start_date >= ? AND start_date <= ?',
                                  @search_date.beginning_of_month,
                                  @search_date.end_of_month).order(start_date: :asc)
  end

  def search_params
    params.permit(:search_date)
  end

  def search_date
    year = search_params.present? ? search_params['search_date(1i)'].to_i : Time.now.year
    month = search_params.present? ? search_params['search_date(2i)'].to_i : Time.now.month

    @search_date = DateTime.new(year, month, 1)
  end

  def members
    @members ||= Member.all
  end

  def new_period_start_date
    return Time.current.beginning_of_day if OnCallPeriod.count.zero?

    (OnCallPeriod.last.end_date.to_date + 1.day).beginning_of_day
  end
end

app/controllers/on_call_units_controller.rb
# frozen_string_literal: true

class OnCallUnitsController < ApplicationController
  def edit
    @unit = OnCallUnit.find(edit_params[:id])
    @other_units = OnCallUnit.where(on_call_period_id: @unit.on_call_period_id)
                             .order(start_date: :asc)
                             .reject { |unit| unit.member_id == @unit.member_id }
  end

  def update # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
    init_units

    ActiveRecord::Base.transaction do
      selected_member_id = @selected_unit.member_id
      @selected_unit.member_id = @target_unit.member_id
      @selected_unit.save!

      @target_unit.member_id = selected_member_id
      @target_unit.save!
    end

    flash[:success] = 'Schedule swapped successfully.'
    redirect_to root_path
  rescue StandardError => e
    Rails.logger.error e
    flash[:error] = 'Invalid parameters passed.'
    redirect_back(fallback_location: edit_on_call_unit_path(update_params[:id]))
  end

  private

  def edit_params
    params.permit(:id)
  end

  def update_params
    params.permit(:id, :selected_unit_id)
  end

  def init_units
    @target_unit = OnCallUnit.find(update_params[:id])
    @selected_unit = OnCallUnit.find(update_params[:selected_unit_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<div class="container w-full">
  <!-- This example requires Tailwind CSS v2.0+ -->
  <div class="relative bg-white">
    <div class="max-w-7xl mx-auto px-4 sm:px-6">
      <div class="flex justify-between items-center border-b-2 border-gray-100 py-6 md:justify-start md:space-x-10">
        <span>On-call Scheduling</span>
        <nav class="md:flex">
          <a href="<%= root_path %>" class="w-full flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-indigo-600 hover:bg-indigo-700">
            Home
          </a>
        </nav>
      </div>
    </div>
  </div>
  <% if flash.present? %>
    <% flash.each do |key, value| %>
      <div class="bg-indigo-600">
        <div class="max-w-7xl mx-auto py-3 px-3 sm:px-6 lg:px-8">
          <div class="flex items-center justify-between flex-wrap">
            <div class="w-0 flex-1 flex items-center">
              <p class="ml-3 font-medium text-white truncate">
                <span>
                  <%= value %>
                </span>
              </p>
            </div>
            <div class="order-2 flex-shrink-0 sm:order-3 sm:ml-3">
              <button type="button" class="-mr-1 flex p-2 rounded-md hover:bg-indigo-500 focus:outline-none focus:ring-2 focus:ring-white sm:-mr-2">
                <span class="sr-only">Dismiss</span>
                <!-- Heroicon name: outline/x -->
                <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>On-Call Scheduling</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main class="container mx-auto">
      <%= yield %>
    </main>
  </body>
</html>

app/views/on_call_periods/index.html.erb
<%= render partial: "layouts/header" %>
<div class="container w-full">
<% if @schedules.present? %>
  <div class="relative bg-white">
    <div class="max-w-7xl mx-auto px-4 sm:px-6">
      <div class="flex justify-between items-center py-6 md:justify-start md:space-x-10">
        <span>
          <% if @current_on_call_member.present? %>
            <b><%= @current_on_call_member.name %></b> is Today's on-call.
          <% else %>
            There is no on-call today.
          <% end %>
        </span>
      </div>
    </div>
  </div>
  <div class="flex flex-col">
    <div class="relative bg-white">
      <div class="max-w-7xl mx-auto px-4 sm:px-6">
        <div class="flex justify-between items-center md:justify-start md:space-x-10">
          <%= form_with url: root_path, method: :get do |form| %>
            <%= form.date_select :search_date,
                discard_day: true,
                start_year: @first_on_call_date.year,
                end_year: @last_on_call_date.year,
                default: @search_date %>
            <%= form.button "Search schedule", type: :submit, class: 'bg-transparent hover:bg-indigo-600 text-indigo-700 font-semibold hover:text-white py-2 px-4 border border-indigo-600 hover:border-transparent rounded' %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="relative bg-white">
      <div class="max-w-7xl mx-auto px-4 sm:px-6">
        <div class="flex justify-between items-center py-6 md:justify-start md:space-x-10">
          <span class="text-gray-500">
              The last on-call date is <%= @last_on_call_date.strftime('%a, %d %B %Y') %>.
          </span>
        </div>
      </div>
    </div>
  </div>
  <div class="flex flex-col">
    <div class="relative bg-white">
      <div class="max-w-7xl mx-auto px-4 sm:px-6">
        <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
          <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
            <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
              <table class="min-w-full divide-y divide-gray-200">
                <thead class="bg-gray-50">
                  <tr>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Name
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Start Date
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      End Date
                    </th>
                    <th scope="col" class="relative px-6 py-3">
                      <span class="sr-only">Swap</span>
                    </th>
                  </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200">
                  <% @schedules.each do |schedule| %>
                    <tr>
                      <td class="px-6 py-4 whitespace-nowrap">
                        <div class="text-sm font-medium text-gray-900"><%= schedule.member.name %></div>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap">
                        <div class="text-sm text-gray-900"><%= schedule.start_date.strftime('%a, %d %b %Y') %></div>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap">
                        <div class="text-sm text-gray-900"><%= schedule.end_date.strftime('%a, %d %b %Y') %></div>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                        <a href="<%= edit_on_call_unit_path(schedule.id) %>" class="text-indigo-600 hover:text-indigo-900">swap</a>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="flex flex-col">
      <div class="relative bg-white">
        <div class="max-w-7xl mx-auto px-4 sm:px-6">
          <div class="flex justify-between items-center py-6 md:justify-start md:space-x-10">
            <span>There is no schedule.</span>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
  <div class="flex flex-col">
    <div class="relative bg-white">
      <div class="max-w-7xl mx-auto px-4 sm:px-6">
        <div class="flex justify-between items-center py-6 md:justify-start md:space-x-10">
          <%= form_for @on_call_period, url: {action: 'create'} do |form| %>
            <%= form.button "Create a new schedule", type: :submit, class: 'bg-transparent hover:bg-indigo-600 text-indigo-700 font-semibold hover:text-white py-2 px-4 border border-indigo-600 hover:border-transparent rounded' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/on_call_units/edit.html.erb
<%= render partial: "layouts/header" %>
<div class="container w-full">
  <div>
    <div class="relative bg-white">
      <div class="max-w-7xl mx-auto px-4 sm:px-6">
        <div class="flex justify-between items-center py-6 md:justify-start md:space-x-10">
          <span>Target on-call schedule</span>
        </div>
      </div>
    </div>
    <div class="flex flex-col">
      <div class="relative bg-white">
        <div class="max-w-7xl mx-auto px-4 sm:px-6">
          <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
              <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-200">
                  <thead class="bg-gray-50">
                    <tr>
                      <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Name
                      </th>
                      <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Start Date
                      </th>
                      <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        End Date
                      </th>
                    </tr>
                  </thead>
                  <tbody class="bg-white divide-y divide-gray-200">
                    <tr>
                      <td class="px-6 py-4 whitespace-nowrap">
                        <div class="text-sm font-medium text-gray-900"><%= @unit.member.name %></div>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap">
                        <div class="text-sm text-gray-900"><%= @unit.start_date.strftime('%a, %d %b %Y') %></div>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap">
                        <div class="text-sm text-gray-900"><%= @unit.end_date.strftime('%a, %d %b %Y') %></div>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div>
    <div class="relative bg-white">
      <div class="max-w-7xl mx-auto px-4 sm:px-6">
        <div class="flex justify-between items-center py-6 md:justify-start md:space-x-10">
          <span>Select on-call schedule to swap</span>
        </div>
      </div>
    </div>
    <div class="relative bg-white">
      <div class="max-w-7xl mx-auto px-4 sm:px-6">
        <div class="flex justify-between items-center py-6 md:justify-start md:space-x-10">
          <%= form_with url: on_call_unit_path(@unit.id), method: :patch do |form| %>
            <%= form.collection_select :selected_unit_id, @other_units, :id, ->(unit) { "#{unit.member.name}, #{unit.to_date}" } %>
            <%= form.button "Swap", type: :submit, class: 'bg-transparent hover:bg-indigo-600 text-indigo-700 font-semibold hover:text-white py-2 px-4 border border-indigo-600 hover:border-transparent rounded' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>